### ISSUE TITLE
set an entrypoint for arch-mini

### ISSUE THREAD

**Issue by keis** [nfnty/dockerfiles#1]
when starting arch-mini without any arguments it fails because no entrypoint is set. A common approach used by e.g the debian images is to jump into a bash shell.

arch-mini
```
$ docker run -ti nfnty/arch-mini
FATA[0000] Error response from daemon: No command specified
```

debian
```
$ docker run -ti debian
root@fd0a7db6a1bb:/#
```

**Comment by nfnty** [comment]
arch-mini is intended to be used as a base image, whereas `ENTRYPOINT` is used for container images. Debian is using `CMD`, which also seems like a good fit for arch-mini. Thanks.
