### ISSUE TITLE
 pacman --sync --noconfirm --clean --clean does not clean /var/cache/pacman/pkg/

### ISSUE THREAD

**Issue by gutenye** [nfnty/dockerfiles#2]
I tested on my Arch Linux. 

```
#  pacman --sync --noconfirm --clean --clean          

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] 

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...
```

Though it did clean `/var/lib/pacman`, but not `/var/cache/pacman/pkg`, I use `rm -rf /var/cache/pacman/pkg/*` instead.

**Comment by nfnty** [comment]
Very interesting, thanks. This should also be reported upstream. Will implement fix soon.

**Comment by gutenye** [comment]
I've reported https://bbs.archlinux.org/viewtopic.php?pid=1529458#p1529458, the solution is `echo "y\ny" | pacman -Scc`
