### ISSUE TITLE
node

### ISSUE THREAD

**Issue by Sutat** [nfnty/dockerfiles#4]
Hi,

Just a question.
In your nodejs docker version of archlinux, why don't you install the "npm" package ?
I need it, and I was wondering how we can use node without the npm to install dependencies.

My guess is you copy your application into the images WITH his dependicies.
Why do you prefer this approche over the one who you install the application, then run "npm install --production" ?

Thank a lot for your work.

**Comment by nfnty** [comment]
Reason being that the image should contain the least amount of dependencies possible. nodejs is the only dependency for packages that only need the runtime. I usually package everything myself (via pacman) and therefore haven't needed for npm. I added an npm image for you: [nfnty/arch-npm](https://hub.docker.com/r/nfnty/arch-npm/)

**Comment by Sutat** [comment]
Thank you for the answer and the image :)
